apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-argon-deployment
spec:
  selector:
    matchLabels:
      app: synapse-argon
  template:
    metadata:
      labels:
        app: synapse-argon
    spec:
      containers:
        - name: synapse-argon
          image: synapse-argon
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: synapse-argon-aws-credentials
