apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - synapse-creator/deployment-patch.yaml
  - synapse-creator/service-patch.yaml

images:
  - name: synapse-creator
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/synapse-creator
    newTag: "45aecfe"

namePrefix: dev-

resources:
  - ../bases
