apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - synapse-creator/deployment-patch.yaml
  - synapse-creator/service-patch.yaml
  - axon-marketplace/deployment-patch.yaml
  - axon-marketplace/service-patch.yaml
  - landing/deployment-patch.yaml
  - landing/service-patch.yaml

images:
  - name: synapse-creator
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/synapse-creator
    newTag: "1e31e1e"
  - name: axon-marketplace
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/axon-marketplace
    newTag: "9dc19b4"
  - name: landing
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/landing
    newTag: "8854d5a"

namespace: dev
namePrefix: dev-

resources:
  - ../bases
