apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - synapse-argon/deployment-patch.yaml
  - synapse-argon/service-patch.yaml

images:
  - name: synapse-argon
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/synapse-argon
    newTag: "6f428ca"

namespace: dev
namePrefix: dev-

resources:
  - ../bases
