apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - synapse-argon/deployment-patch.yaml
  - synapse-argon/service-patch.yaml
  - axon-marketplace/deployment-patch.yaml
  - axon-marketplace/service-patch.yaml
  - landing/deployment-patch.yaml
  - landing/service-patch.yaml

images:
  - name: synapse-argon
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/synapse-argon
    newTag: "9df2ae2"
  - name: axon-marketplace
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/axon-marketplace
    newTag: "801bc77"
  - name: landing
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/landing
    newTag: "b1cfd45"

namespace: dev
namePrefix: dev-

resources:
  - ../bases
