apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nc-beta
  region: us-west-2

vpc:
  id: "vpc-09ec9171"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-west-2a:
        id: "subnet-4f927905"
      us-west-2b:
        id: "subnet-2a10de52"
    private:
      us-west-2c:
        id: "subnet-bf61b8e2"
      us-west-2d:
        id: "subnet-825909a9"

nodeGroups:
  - name: nc-ng-1
    instanceType: t3.medium # vCPU=2 Mem=4Gib
    desiredCapacity: 4
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ["sg-001adc687ad571938"]
    availabilityZones: ["us-west-2a", "us-west-2b"]
  - name: nc-ml
    instanceType: t3.xlarge
    desiredCapacity: 1
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ["sg-001adc687ad571938"]
    availabilityZones: ["us-west-2a", "us-west-2b"]

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
