apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: nc-mini
      containers:
        - name: landing
          env:
            - name: ENVIRONMENT
              value: "production"
