apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - synapse-argon/deployment-patch.yaml
  - synapse-argon/service-patch.yaml
  - axon-marketplace/deployment-patch.yaml
  - axon-marketplace/service-patch.yaml
  - neuron/deployment-patch.yaml
  - neuron/service-patch.yaml
  - landing/deployment-patch.yaml
  - landing/service-patch.yaml

images:
  - name: synapse-argon
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/synapse-argon
    newTag: "62f7e64"
  - name: axon-marketplace
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/axon-marketplace
    newTag: "99384a5"
  - name: neuron
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/neuron
    newTag: "121899c"
  - name: landing
    newName: 471943556279.dkr.ecr.us-west-2.amazonaws.com/landing
    newTag: "d3904b2"

namespace: prod
namePrefix: prod-

resources:
  - ../bases
