apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
spec:
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: landing
          resources:
            requests:
              cpu: "50m"
              memory: "24Mi"
            limits:
              cpu: "50m"
              memory: "24Mi"
          ports:
            - containerPort: 80
