apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-marketplace-deployment
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: nc-main
      containers:
        - name: axon-marketplace
          env:
            - name: ENVIRONMENT
              value: "production"
