apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - synapse-argon/deployment.yaml
  - synapse-argon/service.yaml
  - axon-marketplace/deployment.yaml
  - axon-marketplace/service.yaml
  - neuron/deployment.yaml
  - neuron/service.yaml
  - landing/deployment.yaml
  - landing/service.yaml
