apiVersion: v1
kind: Service
metadata:
  name: axon-marketplace-service
spec:
  selector:
    app: axon-marketplace
  ports:
    - name: https
      port: 80
      targetPort: 8000
  type: LoadBalancer
