apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuron-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: nc-ml
      containers:
        - name: neuron
          env:
            - name: ENVIRONMENT
              value: "production"
