apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuron-deployment
spec:
  selector:
    matchLabels:
      app: neuron
  template:
    metadata:
      labels:
        app: neuron
    spec:
      containers:
        - name: neuron
          image: neuron
          resources:
            requests:
              cpu: "4"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
          ports:
            - containerPort: 5000
