apiVersion: v1
kind: Service
metadata:
  name: synapse-creator-service
spec:
  selector:
    app: synapse-creator
  ports:
    - name: https
      port: 443
      targetPort: 3000
  type: LoadBalancer
