apiVersion: v1
kind: Service
metadata:
  annotations:
  # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  # service.beta.kubernetes.io/aws-load-balancer-ssl-cert:
  name: synapse-creator-service
